name: docker

on:
  workflow_dispatch: # Allows manual trigger
  push:
    tags:
      - 'v*.*.*' # Trigger on push of tags like v1.0.0, v1.2.3, etc.

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        # It's good practice to fetch all tags when working with tag-based triggers
        # especially if the tag might have been created locally and pushed.
        # The default checkout action usually fetches tags, but being explicit can help.
        with:
          fetch-depth: 0 # Fetches all history and tags

      - name: Set up QEMU for multi-platform build
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Get version
        id: get_version
        # This condition is still valid: github.ref will be 'refs/tags/vX.X.X'
        if: startsWith(github.ref, 'refs/tags/v')
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Build and Push Docker image
        if: startsWith(github.ref, 'refs/tags/v')
        uses: docker/build-push-action@v5
        with:
          push: true 
          tags: |
            ghcr.io/${{ github.repository_owner }}/scanservjs:release-${{ steps.get_version.outputs.VERSION }}
            ghcr.io/${{ github.repository_owner }}/scanservjs:${{ steps.get_version.outputs.VERSION }}
            ghcr.io/${{ github.repository_owner }}/scanservjs:latest
          target: scanservjs-core
          platforms: linux/amd64,linux/arm64,linux/arm/v7